DROP TABLE "DHROD0325"."SA_BOARD";
CREATE TABLE "DHROD0325"."SA_BOARD" (
"ID" NUMBER NOT NULL ,
"BOARD_ID" VARCHAR2(200 BYTE) NOT NULL ,
"USER_ID" VARCHAR2(20 BYTE) NOT NULL ,
"PASSWORD" VARCHAR2(30 BYTE) NOT NULL ,
"TITLE" VARCHAR2(200 BYTE) NOT NULL ,
"REG_DATE" DATE NOT NULL ,
"HAS_FILE" VARCHAR2(10 BYTE) NOT NULL ,
"CONTENT" CLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

DROP TABLE "DHROD0325"."SA_BOARD_FILE";
CREATE TABLE "DHROD0325"."SA_BOARD_FILE" (
"NO" NUMBER NOT NULL ,
"ID" NUMBER NOT NULL ,
"FILE_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"FILE_SIZE" NUMBER NOT NULL ,
"FILE_REG_DATE" DATE NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE;

DROP TABLE "DHROD0325"."SA_BOARD_REPLY";
CREATE TABLE "DHROD0325"."SA_BOARD_REPLY" (
"ID" NUMBER NOT NULL ,
"NO" NUMBER NOT NULL ,
"USER_ID" VARCHAR2(20 BYTE) NOT NULL ,
"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ,
"EMAIL" VARCHAR2(20 BYTE) NULL ,
"TITLE" VARCHAR2(200 BYTE) DEFAULT NULL  NULL ,
"REG_DATE" VARCHAR2(40 BYTE) NOT NULL ,
"CONTENT" CLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

DROP TABLE "DHROD0325"."SA_BOARD_TABLES";
CREATE TABLE "DHROD0325"."SA_BOARD_TABLES" (
"ID" NUMBER NOT NULL ,
"BOARD_ID" VARCHAR2(200 BYTE) NOT NULL ,
"BOARD_NM" VARCHAR2(200 BYTE) DEFAULT NULL  NULL ,
"BOARD_DESC" VARCHAR2(200 BYTE) DEFAULT NULL  NULL ,
"THEME" VARCHAR2(200 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

DROP TABLE "DHROD0325"."SA_MEMBER";
CREATE TABLE "DHROD0325"."SA_MEMBER" (
"NO" NUMBER NOT NULL ,
"ID" VARCHAR2(20 BYTE) NOT NULL ,
"PW" VARCHAR2(10 BYTE) NOT NULL ,
"NAME" VARCHAR2(20 BYTE) NOT NULL ,
"ROLE" NUMBER NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE;

DROP SEQUENCE "DHROD0325"."BOARD_REPLY_SEQ";
CREATE SEQUENCE "DHROD0325"."BOARD_REPLY_SEQ"
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 999999999999999999999999999
 START WITH 1
 NOCACHE;

DROP SEQUENCE "DHROD0325"."BOARD_SEQ";
CREATE SEQUENCE "DHROD0325"."BOARD_SEQ"
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 999999999999999999999999999
 START WITH 1
 NOCACHE;

DROP SEQUENCE "DHROD0325"."BOARD_TABLE_SEQ";
CREATE SEQUENCE "DHROD0325"."BOARD_TABLE_SEQ"
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 999999999999999999999999999
 START WITH 1
 NOCACHE;

DROP SEQUENCE "DHROD0325"."BOARD_FILE_SEQ";
CREATE SEQUENCE "DHROD0325"."BOARD_FILE_SEQ"
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 999999999999999999999999999
 START WITH 1
 NOCACHE; 

DROP SEQUENCE "DHROD0325"."SA_MEMBER_SEQ";
CREATE SEQUENCE "DHROD0325"."SA_MEMBER_SEQ"
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 999999999999999999999999999
 START WITH 1
 NOCACHE; 

DROP SEQUENCE "DHROD0325"."SA_MEMBER_ROLE_SEQ";
CREATE SEQUENCE "DHROD0325"."SA_MEMBER_ROLE_SEQ"
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 999999999999999999999999999
 START WITH 1
 NOCACHE;  
 
DROP SEQUENCE "DHROD0325"."LINENUM";
CREATE SEQUENCE "DHROD0325"."LINENUM"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999999999999999999999999
 START WITH 1
 CACHE 10000;

DROP SEQUENCE "DHROD0325"."ORDERNUM";
CREATE SEQUENCE "DHROD0325"."ORDERNUM"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999999999999999999999999
 START WITH 1
 CACHE 10000;
 
ALTER TABLE "DHROD0325"."SA_BOARD" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD" ADD CHECK ("BOARD_ID" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD" ADD CHECK ("USER_ID" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD" ADD CHECK ("TITLE" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD" ADD CHECK ("REG_DATE" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD" ADD CHECK ("HAS_FILE" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD" ADD PRIMARY KEY ("ID");

ALTER TABLE "DHROD0325"."SA_BOARD_FILE" ADD CHECK ("NO" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_FILE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_FILE" ADD CHECK ("FILE_NAME" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_FILE" ADD CHECK ("FILE_SIZE" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_FILE" ADD CHECK ("FILE_REG_DATE" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_FILE" ADD PRIMARY KEY ("NO");

ALTER TABLE "DHROD0325"."SA_BOARD_REPLY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_REPLY" ADD CHECK ("NO" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_REPLY" ADD CHECK ("USER_ID" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_REPLY" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_REPLY" ADD CHECK ("REG_DATE" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_REPLY" ADD PRIMARY KEY ("ID");

ALTER TABLE "DHROD0325"."SA_BOARD_TABLES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_TABLES" ADD CHECK ("BOARD_ID" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_TABLES" ADD CHECK ("THEME" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_BOARD_TABLES" ADD PRIMARY KEY ("ID");

ALTER TABLE "DHROD0325"."SA_MEMBER" ADD CHECK ("NO" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_MEMBER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_MEMBER" ADD CHECK ("PW" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_MEMBER" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_MEMBER" ADD CHECK ("ROLE" IS NOT NULL);
ALTER TABLE "DHROD0325"."SA_MEMBER" ADD PRIMARY KEY ("NO");

ALTER TABLE "DHROD0325"."SA_BOARD_FILE" ADD FOREIGN KEY ("NO") REFERENCES "DHROD0325"."SA_BOARD" ("ID") ON DELETE CASCADE;
ALTER TABLE "DHROD0325"."SA_BOARD_REPLY" ADD FOREIGN KEY ("NO") REFERENCES "DHROD0325"."SA_BOARD" ("ID") ON DELETE CASCADE;
